/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 407aef604503d8a6033fa61e73e21bf4)
// Runtime types generated with workerd@1.20250508.0 2025-04-04 global_fetch_strictly_public,nodejs_compat
declare namespace Cloudflare {
	interface Env {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		BEUTL_R2_BUCKET: R2Bucket;
		WORKER_SELF_REFERENCE: Fetcher /* beutl-web */;
		BEUTL_DATABASE_HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
