/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv` (hash: 982bf429eb67ff852121f22fdb58f82c)
// Runtime types generated with workerd@1.20250508.0 2025-04-04 global_fetch_strictly_public,nodejs_compat
declare namespace Cloudflare {
	interface Env {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		BEUTL_R2_BUCKET: R2Bucket;
		WORKER_SELF_REFERENCE: Fetcher /* beutl-web */;
    BEUTL_DATABASE_HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
