"use client";
import { useState, useTransition } from "react";
import { Button } from "@beutl/ui/ui/button";
import { resumeStorageMultipartCleanup, terminalizeStorageMultipartCleanup } from "./actions";
type Row = { objectKey: string; uploadId: string; attempts: number; lastError: string | null; interventionAt: Date; revision: number };
export function StorageMultipartInterventions({ rows }: { rows: Row[] }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null); const [reason, setReason] = useState(""); const [evidence, setEvidence] = useState("");
  const run = (row: Row, terminalize: boolean) => startTransition(async () => { if (terminalize && (!reason.trim() || !evidence.trim() || !window.confirm("Terminalizing preserves this handle as terminal and acknowledges that remote proof was not supplied. Continue?"))) return; const result = await (terminalize ? terminalizeStorageMultipartCleanup : resumeStorageMultipartCleanup)({ objectKey: row.objectKey, uploadId: row.uploadId, expectedRevision: row.revision, expectedInterventionAt: row.interventionAt.toISOString(), ...(terminalize ? { operatorReason: reason, operatorEvidence: evidence } : {}) }); setMessage(result.message ?? (result.success ? "Saved" : "Failed")); if (result.success) window.location.reload(); });
  if (!rows.length) return <p className="text-sm text-muted-foreground">No multipart cleanup interventions.</p>;
  return <div className="flex flex-col gap-3">{message && <p className="text-sm text-muted-foreground">{message}</p>}{rows.map((row) => <div key={`${row.objectKey}:${row.uploadId}`} className="rounded-lg border p-4 text-sm"><p className="font-medium break-all">{row.objectKey}</p><p className="break-all">upload: {row.uploadId}</p><p className="text-muted-foreground">attempts: {row.attempts}; {row.lastError ?? "unknown error"}</p><textarea className="mt-2 min-h-16 w-full rounded border p-2" placeholder="Required reason (10+ characters)" value={reason} onChange={(event) => setReason(event.target.value)} /><textarea className="mt-2 min-h-16 w-full rounded border p-2" placeholder="Evidence or ticket reference (10+ characters)" value={evidence} onChange={(event) => setEvidence(event.target.value)} /><div className="mt-2 flex gap-2"><Button size="sm" disabled={pending} onClick={() => run(row, false)}>Resume</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => run(row, true)}>Terminalize (acknowledge risk)</Button></div></div>)}</div>;
}
