"use client";
import { useState, useTransition } from "react";
import { Button } from "@beutl/ui/ui/button";
import { terminalizeOrphanTopUpResolution } from "./actions";
type Row = { resolution: { topUpAttemptId: string; ownerUserId: string; stripeCustomerId: string; billingOfferId: string; revision: number; expectedPaymentIntentIds: string; lastError: string | null }; attempt: unknown };
export function TopUpResolutionInterventions({ rows }: { rows: Row[] }) {
  const [pending, startTransition] = useTransition(); const [reason, setReason] = useState(""); const [evidence, setEvidence] = useState(""); const [message, setMessage] = useState<string | null>(null);
  if (!rows.length) return <p className="text-sm text-muted-foreground">No top-up checkout interventions.</p>;
  return <div className="flex flex-col gap-3">{message && <p className="text-sm text-muted-foreground">{message}</p>}{rows.map(({ resolution, attempt }) => <div key={resolution.topUpAttemptId} className="rounded-lg border p-4 text-sm"><p className="font-mono break-all">attempt: {resolution.topUpAttemptId}</p><p className="font-mono break-all">owner: {resolution.ownerUserId} · {attempt ? "attempt present" : "orphaned attempt"}</p><p className="text-muted-foreground">revision {resolution.revision}; expected PaymentIntents: {resolution.expectedPaymentIntentIds || "[]"}</p><p>{resolution.lastError ?? "operator intervention required"}</p><textarea className="mt-2 min-h-16 w-full rounded border p-2" placeholder="Required reason (10+ characters)" value={reason} onChange={(event) => setReason(event.target.value)} /><textarea className="mt-2 min-h-16 w-full rounded border p-2" placeholder="Evidence or ticket reference (10+ characters)" value={evidence} onChange={(event) => setEvidence(event.target.value)} /><Button size="sm" disabled={pending} onClick={() => startTransition(async () => { const result = await terminalizeOrphanTopUpResolution({ topUpAttemptId: resolution.topUpAttemptId, ownerUserId: resolution.ownerUserId, stripeCustomerId: resolution.stripeCustomerId, billingOfferId: resolution.billingOfferId, expectedRevision: resolution.revision, operatorReason: reason, operatorEvidence: evidence }); setMessage(result.message ?? (result.success ? "Saved" : "Failed")); if (result.success) window.location.reload(); })}>Terminalize after refund proof</Button></div>)}</div>;
}
