name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v4

    - run: pnpm install

    - run: pnpm run build

    - run: |
        mkdir ./build
        cp -r ./.next/standalone/. ./build
        cp -r ./.next/static ./build/.next/static
        cp -r ./public ./build/public
        cp ./next.config.mjs ./build
        cd ./build
        zip -r build.zip ./

    - uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/build.zip,prisma/schema.prisma"
        target: /var/www/

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd /var/www
          mkdir -p beutl-clientapp-tmp
          rm -rf beutl-clientapp-tmp/*
          cd beutl-clientapp-tmp
          unzip ../build.zip
          cp ../beutl-clientapp-v3/.env ./
          pnpm i
          mkdir prisma
          mv ../schema.prisma ./prisma/
          pnpm dlx prisma generate
          systemctl stop nextjs-beutl-client-v3
          cd /var/www
          rm -rf beutl-clientapp-v3
          mv beutl-clientapp-tmp beutl-clientapp-v3
          chmod -R 777 beutl-clientapp-v3
          systemctl start nextjs-beutl-client-v3
