name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd /var/www/beutl-clientapp-v3
          git fetch && git pull
          cp -R ./ ../beutl-clientapp-tmp
          cd ../beutl-clientapp-tmp
          pnpm install
          pnpm build
          systemctl stop nextjs-beutl-client-v3
          cd /var/www
          rm -rf beutl-clientapp-v3
          mv beutl-clientapp-tmp beutl-clientapp-v3
          systemctl start nextjs-beutl-client-v3
